#pragma config(Motor,  motorA,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void clearEncoder(){
		//clear encoder
	nMotorEncoder[left]=0;
	nMotorEncoder[right]=0;
}
void count(int dis)
{
	dis/=17.27;
	dis*=360
	return dis;
}
void stop_robot(){
	//motor stop
	motor[left]=0;
	motor[right]=0;
	wait1Msec(1500);
}

void turnl(){
	while(nMotorEncoder[right]<460){
		motor[left]=0;
		motor[right]=50;
	}
}

void turnr(){
	while(nMotorEncoder[left]<460){
		motor[left]=50;
		motor[right]=0;
}
}

task main()
{
 	clearEncoder();

 	//set target
	while(nMotorEncoder[left]<750 && nMotorEncoder[right]<750)
	{
		motor[left]=70;//motor move forward
		motor[right]=70;
	}


	stop_robot();
	clearEncoder();

	turnl();

	stop_robot();
	clearEncoder();

	while(nMotorEncoder[left]<1100 && nMotorEncoder[right]<1100)
	{
		motor[left]=70;//motor move forward
		motor[right]=70;
	}

	stop_robot();
	clearEncoder();

	turnr();

	stop_robot();
	clearEncoder();

	while(nMotorEncoder[left]<450 && nMotorEncoder[right]<450)
	{
		motor[left]=70;//motor move forward
		motor[right]=70;
	}

	stop_robot();
	clearEncoder();

	turnr();

	stop_robot();
	clearEncoder();

	while(nMotorEncoder[left]<625 && nMotorEncoder[right]<625)
	{
		motor[left]=70;//motor move forward
		motor[right]=70;
	}

	stop_robot();
	clearEncoder();
}
