#pragma config(Motor,  motorB,          rm,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          lm,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void straight()
{
		motor[rm]=50;
		motor[lm]=50;
		wait1Msec(4500);
}

void stopr()
{
		motor[lm]=0;
		motor[rm]=0;
		wait1Msec(2000);
}

void turnr()
{
		motor[rm]=0;
		motor[lm]=50;
		wait1Msec(1400);
}

task main()
{
	for(int i=0;i<4;i++)
	{
		straight();
		stopr();
		turnr();
		stopr();

		straight();
		stopr();
		turnr();
		stopr();

		straight();
		stopr();
		turnr();
		stopr();

		straight();
		stopr();
		turnr();
		stopr();
	}
}
