#pragma config(Motor,  motorB,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          l,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void stopr()
{
	motor[r]=0;
	motor[l]=0;
	wait1Msec(1500);
}

void clear()
{
	nMotorEncoder[l]=0;
	nMotorEncoder[r]=0;
}

void turn()
{
	while(nMotorEncoder[l]<460)
	{
		motor[r]=0;
		motor[l]=50;
	}
}

task main()
{
	for(int i=0; i<2; i++)
	{
		clear();
		while(nMotorEncoder[l]<1600 && nMotorEncoder[r]<1600)
		{
			motor[r]=50;
			motor[l]=50;
		}
		stopr();
		clear();
		turn();
		stopr();
		clear();
		while(nMotorEncoder[l]<1600 && nMotorEncoder[r]<1600)
		{
			motor[r]=50;
			motor[l]=50;
		}
		stopr();
		clear();
		turn();
		stopr();
		clear();

		while(nMotorEncoder[l]<1600 && nMotorEncoder[r]<1600)
		{
			motor[r]=50;
			motor[l]=50;
		}
		stopr();
		clear();
		turn();
		stopr();
		clear();

		while(nMotorEncoder[l]<1600 && nMotorEncoder[r]<1600)
		{
			motor[r]=50;
			motor[l]=50;
		}
		stopr();
		clear();
		turn();
		stopr();
		clear();
	}
}
