#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          l,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void straight()
{
	motor[r]=50;
	motor[l]=50;
}

void stopr()
{
	motor[r]=0;
	motor[l]=0;
	wait1Msec(1500);
}

void turn()
{
	nMotorEncoder[l]=0;
	nMotorEncoder[r]=0;
	while(nMotorEncoder[l]<900)
	{
		motor[r]=0;
		motor[l]=50;
	}
}

void turnl()
{
	nMotorEncoder[l]=0;
	nMotorEncoder[r]=0;
	while(nMotorEncoder[r]<900)
	{
		motor[r]=50;
		motor[l]=0;
	}
}


task main()
{
	while(SensorValue(sonar)>30)
	{
		straight();
	}
	stopr();
	turn();
	stopr();
	//------------------------
	while(SensorValue(sonar)>30)
	{
		straight();
	}
	stopr();
	turnl();
	stopr();

	//------------------------
	while(SensorValue(sonar)>30)
	{
		straight();
	}
	stopr();
	turn();
	stopr();

	//------------------------
	while(SensorValue(sonar)>30)
	{
		straight();
	}
	stopr();
}
