#pragma config(Sensor, S4,     ultra,          sensorSONAR)
#pragma config(Motor,  motorB,          right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          left,          tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void clear()
{
    nMotorEncoder[left]=0;
    nMotorEncoder[right]=0;
}
task main()
{
 	int count=0;
   clear();
   while(nMotorEncoder[left]<1850 && nMotorEncoder[right] <1850)
   {
     motor[left]=40;
     motor[right]=40;
     if(SensorValue(ultra)<50)
     count++;
   }
   clear();
   while(nMotorEncoder[left]<425 && nMotorEncoder[right]<425)
   {
     motor[left]=50;
     motor[right]=-50;
   }
 	 clear();
   while(nMotorEncoder[left]<1850)
   {
     motor[left]=40;
     motor[right]=40;
     if(SensorValue(ultra)<50)
     count++;
   }
   nxtDisplayCenteredTextLine(1,"Attendance%d",count);
}
