#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          r,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          l,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		if(SensorValue(sonar)>30)
		{
			motor[l]=random(100);
			motor[r]=random(100);
		}
		else
		{
			motor[l]=0;
			motor[r]=random(100);
			wait1Msec(random(1500);
		}
	}
}
